### ISSUE TITLE
Home Assistant as notifier: how to include the images?

### ISSUE THREAD

**Issue by glc650** [djdd87/SynoAI#216]
My SynoAI config has Home Assistant configured as a notifier:
```
      {
        "Type": "Webhook",
        "Url": "https://ha_dns_name:8123/api/webhook/push_synoai_driveway-cam"
      }
```

In HA I have this in my configuration.yaml:
```
camera:
  - platform: push
    name: push SynoAI driveway-cam
    webhook_id: push_synoai_driveway-cam
    timeout: 1
    buffer: 1
```

With an automation configured to use it as a trigger:
```
alias: SynoAI movement detected notification
description: ""
trigger:
  - platform: state
    entity_id:
      - camera.push_synoai_driveway_cam
    from: idle
    to: recording
action:
  - service: notify.mobile_app_my_cell
    data:
      message: "SynoAI: movement detected (driveway-cam)"
mode: single
```

This works fine except I don't get images with the notifications.  How do I attach the image from SynoAI to these notifications?  I'm not even sure where HA is saving them?
