### ISSUE TITLE
SSS action Rule: cannot execute the Webhock

### ISSUE THREAD

**Issue by AlexanderSch90** [djdd87/SynoAI#33]
Hello everybody,
I have a problem that the action rule within SSS cannot execute the Webhock. 
Synology has the IP: 10.4.90.10 and the docker container with SynoAI has the IP 10.4.4.202. I created a rule in the router / firewall so that SSS can access SynoAI. I also see a log entry there when I want to test the action rule. Are there problems if the same subnet is not used?
How can I continue testing? Can I simulate a webhook from the IP range SSS differently? How does it work?

Thanks!

**Comment by djdd87** [comment]
Hi, it just calls the web hook at the IP/URL you specify; nothing clever. You say there's a log entry - a log entry where? In SynoAI? What error are you getting?

**Comment by AlexanderSch90** [comment]
I mean a log entry in the firewall that the communication is free.
My webhook looks like this: http://10.4.4.202:82/Camera/Hof
When I enter this in the browser, the website cannot be reached. There is also no log in the Docker container SynoAI.
Is that right?

I mapped the port from 82 to 80 in the container.

**Comment by djdd87** [comment]
Is that the entire log from SynoAI?

**Comment by AlexanderSch90** [comment]
yes

**Comment by djdd87** [comment]
There should at least something after Querying end points, even if it is an error message.

Set your logs to Debug, restart the container and provide the full logs.

**Comment by AlexanderSch90** [comment]
I made it within the "appsettings.json". The logs haven't changed.
Here are the appsettings.json:

```
{
  "AllowedHosts": "*",

  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Debug"
    }
  },

  "Url": "http://10.4.90.10:5000",
  "User": "alexander",
  "Password": "...",
  "AllowInsecureUrl": false,

  "Delay": 5000,
  "DrawMode": "Matches",

  "AI": {
    "Type": "DeepStack",
    "Url": "http://10.4.4.202:83",
    "MinSizeX": 10,
    "MinSizeY": 10
  },

  "Notifiers": [
    {
      "Type": "Webhook",
      "Url": "http://10.4.4.13:8082/set/0_userdata.0.TEST?value=1",
	    "Method": "GET",
      "SendImage": false,
      "SendTypes": false
    }
  ],

  "Cameras": [
    {
      "Name": "Hauseingang",
      "Types": [ "Person" ],
      "Threshold": 50,
      "MinSizeX": 25,
      "MinSizeY": 50
    },
    {
      "Name": "Hof",
      "Types": [ "Car", "Truck" ],
      "Threshold": 75
    }
  ]
}
```

And the docker-compose:
```

version: "3.8"
services:
  synoai:
    volumes:
      - /media/synodocker/objekterkennung/synoai/captures:/app/Captures
      - /media/synodocker/objekterkennung/synoai/appsettings.json:/app/appsettings.json

    ports:
      - 82:80
    image: djdd87/synoai:latest
    container_name: synoai
    restart: unless-stopped
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    container_name: deepstackai
    restart: unless-stopped
    ports:
      - 83:5000
    environment:
      - VISION-DETECTION=True
      - MODE=Low
```
